# Generated by Django 5.0.7 on 2024-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default="yo'q", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
