# Generated by Django 5.0.7 on 2024-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_discount_product_payment_product_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='reserve',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
