# Generated by Django 5.0.7 on 2024-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_product_payment_alter_product_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
